#!/usr/bin/env python3
"""
Wahapedia Datasheet PDF Printer
====================================
Creates a PDF with two Wahapedia datasheets per DIN A4 page.
All datasheets are scaled to the *same physical size* (consistent width),
so all printed cards have identical dimensions — perfect for high-quality
photo paper prints.

Requirements:
- Google Chrome (for headless rendering)
- Python packages: Pillow, reportlab, numpy (usually already installed or via pip install)
- The 4 CSS files (fonts16.css, header16.css, main16.css, profile16.css) must
  be in the same folder as the HTML files (or in the CSS folder).

Usage:
    python3 datasheet_pdf_generator.py Rubric-Marines.html Thunderwolf-Cavalry.html
    python3 datasheet_pdf_generator.py --input-dir ./path_to_my_datasheets --target-width-mm 200 --margin-mm 4 --gap-mm 4
    python3 datasheet_pdf_generator.py --input-dir ./path_to_my_datasheets --output army_book.pdf --target-width-mm 200 --margin-mm 4 --gap-mm 4

The HTML files should be the ones generated by wahapedia_datasheet_printer.py
(with the correct CSS links).
"""

import argparse
import subprocess
import os
import sys
import tempfile
import shutil
from pathlib import Path
from typing import List, Tuple, Optional

import numpy as np
from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader


def find_chrome_binary() -> str:
    """Searches for an available Chrome/Chromium binary on Linux/macOS/Windows."""
    # 1. Environment variable has highest priority
    env_bin = os.environ.get("CHROME_BIN") or os.environ.get("GOOGLE_CHROME_BIN")
    if env_bin and Path(env_bin).exists():
        return env_bin

    # 2. Common names via which
    candidates = [
        "google-chrome",
        "google-chrome-stable",
        "google-chrome-beta",
        "chromium",
        "chromium-browser",
        "google-chrome-unstable",
    ]
    for name in candidates:
        path = shutil.which(name)
        if path:
            return path

    # 3. Common absolute paths (Linux)
    common_paths = [
        "/usr/bin/google-chrome",
        "/usr/bin/google-chrome-stable",
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser",
        "/snap/bin/chromium",
        "/snap/bin/google-chrome",
        "/opt/google/chrome/google-chrome",
        "/opt/google/chrome-beta/google-chrome",
        "/usr/local/bin/google-chrome",
    ]
    for p in common_paths:
        if Path(p).exists():
            return p

    return ""


def render_html_to_png(
    html_path: Path,
    css_dir: Path,
    output_png: Path,
    chrome_binary: str,
    window_width: int = 2400,
    window_height: int = 4000,
    timeout: int = 90
) -> bool:
    """Renders an HTML file with Chrome Headless to a high-resolution PNG."""
    if not chrome_binary:
        print("[ERROR] No Chrome binary provided.")
        return False

    with tempfile.TemporaryDirectory(prefix="wahaprint_") as tmp:
        tmp_path = Path(tmp)
        # Copy HTML and CSS files into temp (so relative paths work)
        shutil.copy2(html_path, tmp_path / html_path.name)
        for css_name in ["fonts16.css", "header16.css", "main16.css", "profile16.css"]:
            src_css = css_dir / css_name
            if src_css.exists():
                shutil.copy2(src_css, tmp_path / css_name)
            else:
                # Fallback: look in the same folder as the HTML
                src_css2 = html_path.parent / css_name
                if src_css2.exists():
                    shutil.copy2(src_css2, tmp_path / css_name)

        html_file = tmp_path / html_path.name
        cmd = [
            chrome_binary,
            "--headless",
            "--disable-gpu",
            "--no-sandbox",
            "--disable-software-rasterizer",
            "--disable-dev-shm-usage",
            "--disable-extensions",
            "--disable-sync",
            "--disable-background-networking",
            "--disable-default-apps",
            "--no-first-run",
            f"--window-size={window_width},{window_height}",
            f"--screenshot={output_png.absolute()}",
            f"file://{html_file.absolute()}"
        ]
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout
            )
            if result.returncode != 0 and "written to file" not in (result.stderr or ""):
                print(f"[WARN] Chrome return code {result.returncode} for {html_path.name}")
                if result.stderr:
                    print(result.stderr[-800:])
        except subprocess.TimeoutExpired:
            print(f"[ERROR] Timeout while rendering {html_path.name}")
            return False

    return output_png.exists() and output_png.stat().st_size > 10000


def auto_crop_to_content(input_png: Path, output_png: Path, padding: int = 12) -> Optional[Tuple[int, int]]:
    """Crops the image to the actual content (removes large empty margins)."""
    try:
        img = Image.open(input_png).convert("RGB")
    except Exception as e:
        print(f"[ERROR] Cannot open image: {e}")
        return None

    arr = np.array(img)
    # Content = everything that is clearly darker than near-white
    mask = np.any(arr < 242, axis=2)
    if not mask.any():
        shutil.copy2(input_png, output_png)
        return img.size

    rows = np.any(mask, axis=1)
    cols = np.any(mask, axis=0)
    rmin, rmax = np.where(rows)[0][[0, -1]]
    cmin, cmax = np.where(cols)[0][[0, -1]]

    # Add padding and clamp
    rmin = max(0, rmin - padding)
    rmax = min(img.height - 1, rmax + padding)
    cmin = max(0, cmin - padding)
    cmax = min(img.width - 1, cmax + padding)

    cropped = img.crop((cmin, rmin, cmax + 1, rmax + 1))
    cropped.save(output_png, "PNG", optimize=True)
    return cropped.size


def find_max_target_width(
    aspects: List[float],
    pair_indices: List[Tuple[int, Optional[int]]],
    gap_mm: float = 8.0,
    margin_mm: float = 12.0,
    max_try: float = 155.0,
    min_try: float = 105.0,
    step: float = 1.0
) -> float:
    """Determines the largest width (mm) at which all pairs still fit on one A4 page."""
    page_h_mm = 297.0
    avail_h_mm = page_h_mm - 2 * margin_mm

    best_w = min_try
    w = max_try
    while w >= min_try:
        fits_all = True
        for idx1, idx2 in pair_indices:
            h1 = aspects[idx1] * w
            h2 = aspects[idx2] * w if idx2 is not None else 0.0
            total_h = h1 + h2 + (gap_mm if idx2 is not None else 0.0)
            if total_h > avail_h_mm:
                fits_all = False
                break
        if fits_all:
            best_w = w
            break  # largest value found (searching downwards)
        w -= step

    return round(best_w, 1)


def create_2up_pdf(
    png_pairs: List[Tuple[Path, Optional[Path]]],
    output_pdf: Path,
    target_width_mm: float,
    gap_mm: float = 8.0,
    margin_mm: float = 12.0,
    title: str = "Wahapedia Datasheets"
):
    """Creates the final 2-up PDF with consistent scaling."""
    page_w_pt, page_h_pt = A4
    target_w_pt = target_width_mm * mm
    left_x = (page_w_pt - target_w_pt) / 2   # centered

    c = canvas.Canvas(str(output_pdf), pagesize=A4)
    c.setTitle(title)
    c.setAuthor("Wahapedia 2-up Printer")

    for page_num, (png_top, png_bottom) in enumerate(png_pairs, 1):
        if page_num > 1:
            c.showPage()

        # Top datasheet
        img1 = Image.open(png_top)
        w1, h1 = img1.size
        aspect1 = h1 / float(w1)
        h1_pt = aspect1 * target_w_pt
        y1 = page_h_pt - margin_mm * mm - h1_pt

        c.drawImage(
            ImageReader(img1),
            left_x,
            y1,
            width=target_w_pt,
            height=h1_pt,
            preserveAspectRatio=True,
            mask='auto'
        )

        # Bottom datasheet (if present)
        if png_bottom:
            img2 = Image.open(png_bottom)
            w2, h2 = img2.size
            aspect2 = h2 / float(w2)
            h2_pt = aspect2 * target_w_pt
            y2 = y1 - gap_mm * mm - h2_pt

            if y2 < margin_mm * mm:
                print(f"[WARN] Page {page_num}: Bottom datasheet may not fit perfectly (too tall).")

            c.drawImage(
                ImageReader(img2),
                left_x,
                y2,
                width=target_w_pt,
                height=h2_pt,
                preserveAspectRatio=True,
                mask='auto'
            )

        # Small page number at the bottom
        c.setFont("Helvetica", 8)
        c.setFillColorRGB(0.4, 0.4, 0.4)
        c.drawCentredString(page_w_pt / 2, 6 * mm, f"Page {page_num}")

    c.save()
    print(f"\n✅ PDF created: {output_pdf.resolve()}")
    print(f"   Every card has a width of {target_width_mm} mm on paper (consistent).")


def main():
    parser = argparse.ArgumentParser(
        description="Creates a PDF with 2 Wahapedia datasheets per A4 page in consistent size.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 datasheet_pdf_generator.py Rubric-Marines.html Thunderwolf-Cavalry.html
  python3 datasheet_pdf_generator.py --input-dir ./path_to_my_datasheets --target-width-mm 200 --margin-mm 4 --gap-mm 4
  python3 datasheet_pdf_generator.py --input-dir ./path_to_my_datasheets --output army_book.pdf --target-width-mm 200 --margin-mm 4 --gap-mm 4
"""
    )
    parser.add_argument("html_files", nargs="*", help="One or more HTML files (in processing order)")
    parser.add_argument("--input-dir", type=Path, help="Folder containing many .html files (will be sorted alphabetically)")
    parser.add_argument("--output", "-o", type=Path, default=Path("wahapedia_datasheets_2up.pdf"),
                        help="Output PDF file (default: wahapedia_datasheets_2up.pdf)")
    parser.add_argument("--target-width-mm", type=float, default=142.0,
                        help="Desired width of each card in mm (default: 142). Starting value when using --auto-maximize.")
    parser.add_argument("--auto-maximize", action="store_true",
                        help="Automatically determine the largest possible width so that all pairs fit on one page.")
    parser.add_argument("--gap-mm", type=float, default=7.0, help="Gap between the two cards (mm)")
    parser.add_argument("--margin-mm", type=float, default=11.0, help="Margin on all sides (mm)")
    parser.add_argument("--css-dir", type=Path, help="Folder containing the CSS files (if not next to the HTML files)")
    parser.add_argument("--keep-temp", action="store_true", help="Do not delete temporary files (for debugging)")
    parser.add_argument("--force-rerender", action="store_true", help="Always re-render (disable cache)")

    args = parser.parse_args()

    # === Find Chrome binary ===
    chrome_bin = find_chrome_binary()
    if not chrome_bin:
        print("[ERROR] No Google Chrome or Chromium found!")
        print("Please install one of the following:")
        print("  sudo apt update && sudo apt install chromium-browser")
        print("  # or")
        print("  sudo apt install google-chrome-stable")
        print("\nAlternatively set the environment variable:")
        print("  export CHROME_BIN=/usr/bin/chromium")
        print("\nOr start with:")
        print("  CHROME_BIN=/path/to/chrome python3 datasheet_pdf_generator.py ...")
        sys.exit(1)
    print(f"Using browser: {chrome_bin}")

    # Collect HTML files
    html_paths: List[Path] = []
    if args.input_dir:
        html_paths = sorted(args.input_dir.glob("*.html"))
        if not html_paths:
            print(f"[ERROR] No .html files found in {args.input_dir}.")
            sys.exit(1)
    elif args.html_files:
        html_paths = [Path(f) for f in args.html_files]
    else:
        print("[ERROR] Please provide HTML files or use --input-dir.")
        parser.print_help()
        sys.exit(1)

    for hp in html_paths:
        if not hp.exists():
            print(f"[ERROR] File not found: {hp}")
            sys.exit(1)

    css_dir = args.css_dir or html_paths[0].parent

    print(f"Processing {len(html_paths)} datasheet(s)...")
    print(f"CSS folder: {css_dir}")

    work_dir = Path(tempfile.mkdtemp(prefix="wahaprint_work_"))
    print(f"Working directory: {work_dir}")

    rendered_pngs: List[Path] = []
    aspects: List[float] = []
    stems: List[str] = []

    for html_path in html_paths:
        stem = html_path.stem
        raw_png = work_dir / f"{stem}_raw.png"
        cropped_png = work_dir / f"{stem}_cropped.png"

        if cropped_png.exists() and not args.force_rerender:
            print(f"  [Cache] {stem}")
        else:
            print(f"  [Render] {stem} ...", end=" ", flush=True)
            ok = render_html_to_png(html_path, css_dir, raw_png, chrome_bin)
            if not ok:
                print("ERROR during rendering!")
                continue
            size = auto_crop_to_content(raw_png, cropped_png)
            if size:
                print(f"OK ({size[0]}x{size[1]} px)")
            else:
                print("Cropping failed, using original.")
                shutil.copy2(raw_png, cropped_png)

        # Aspect ratio after cropping
        try:
            with Image.open(cropped_png) as im:
                w, h = im.size
                aspects.append(h / float(w))
                rendered_pngs.append(cropped_png)
                stems.append(stem)
        except Exception as e:
            print(f"[ERROR] {stem}: {e}")

    if not rendered_pngs:
        print("[ERROR] No usable datasheets were rendered.")
        sys.exit(1)

    # Build pairs
    png_pairs: List[Tuple[Path, Optional[Path]]] = []
    pair_indices: List[Tuple[int, Optional[int]]] = []
    for j in range(0, len(rendered_pngs), 2):
        p1 = rendered_pngs[j]
        p2 = rendered_pngs[j + 1] if j + 1 < len(rendered_pngs) else None
        png_pairs.append((p1, p2))
        idx2 = j + 1 if j + 1 < len(rendered_pngs) else None
        pair_indices.append((j, idx2))

    # Determine target width
    if args.auto_maximize and len(png_pairs) > 0:
        target_w = find_max_target_width(
            aspects, pair_indices,
            gap_mm=args.gap_mm,
            margin_mm=args.margin_mm,
            max_try=min(args.target_width_mm + 15, 158),
            min_try=108
        )
        print(f"Auto-Maximize: {target_w} mm (largest possible for all pairs)")
    else:
        target_w = args.target_width_mm
        print(f"Using fixed width: {target_w} mm")

    # Generate PDF
    create_2up_pdf(
        png_pairs,
        args.output,
        target_width_mm=target_w,
        gap_mm=args.gap_mm,
        margin_mm=args.margin_mm,
        title=f"Wahapedia Datasheets – {len(rendered_pngs)} units"
    )

    if not args.keep_temp:
        shutil.rmtree(work_dir, ignore_errors=True)
        print("Temporary files deleted.")
    else:
        print(f"Temporary files kept at: {work_dir}")


if __name__ == "__main__":
    main()